In [1]:
import numpy as np
import pandas as pd

In [17]:
data = {
    

    "Product": [
        "Laptop","Mouse","Keyboard","Monitor","Laptop",
        "Mouse","Keyboard","Monitor","Laptop","Mouse",
        "Keyboard","Monitor","Laptop","Mouse","Keyboard",
        "Monitor","Laptop","Mouse","Keyboard","Monitor",
        "Laptop","Mouse","Keyboard","Monitor","Laptop",
        "Mouse","Keyboard","Monitor","Laptop","Mouse"
    ],

    "Region": [
        "North","South","East","West","North",
        "South","East","West","North","South",
        "East","West","North","South","East",
        "West","North","South","East","West",
        "North","South","East","West","North",
        "South","East","West","North","South"
    ],

    "Sales": [
        120000,15000,22000,75000,135000,
        18000,28000,85000,150000,21000,
        35000,95000,165000,24000,42000,
        105000,180000,27000,48000,115000,
        195000,30000,55000,125000,210000,
        33000,62000,135000,225000,36000
    ],

    "Units" :np.random.randint(10,100,30),

    "Rep": [
        "Ali","Sara","Ahmed","Ayesha","Bilal",
        "Hamza","Zainab","Usman","Fatima","Hassan",
        "Ali","Sara","Ahmed","Ayesha","Bilal",
        "Hamza","Zainab","Usman","Fatima","Hassan",
        "Ali","Sara","Ahmed","Ayesha","Bilal",
        "Hamza","Zainab","Usman","Fatima","Hassan"
    ],

    "Quarter": [
        "Q1","Q1","Q1","Q1","Q1",
        "Q1","Q1","Q1","Q1","Q1",
        "Q1","Q1","Q1","Q1","Q1",
        "Q2","Q2","Q2","Q2","Q2",
        "Q2","Q2","Q2","Q2","Q2",
        "Q2","Q2","Q2","Q2","Q2"
    ],

    
    "Date": pd.date_range( "05-april,2025",periods = 30)
}

df = pd.DataFrame(data)
df['Month'] = df["Date"].dt.month_name()

df

     Product Region   Sales  Units     Rep Quarter       Date  Month
0     Laptop  North  120000     68     Ali      Q1 2025-04-05  April
1      Mouse  South   15000     45    Sara      Q1 2025-04-06  April
2   Keyboard   East   22000     40   Ahmed      Q1 2025-04-07  April
3    Monitor   West   75000     19  Ayesha      Q1 2025-04-08  April
4     Laptop  North  135000     83   Bilal      Q1 2025-04-09  April
5      Mouse  South   18000     77   Hamza      Q1 2025-04-10  April
6   Keyboard   East   28000     41  Zainab      Q1 2025-04-11  April
7    Monitor   West   85000     41   Usman      Q1 2025-04-12  April
8     Laptop  North  150000     52  Fatima      Q1 2025-04-13  April
9      Mouse  South   21000     76  Hassan      Q1 2025-04-14  April
10  Keyboard   East   35000     38     Ali      Q1 2025-04-15  April
11   Monitor   West   95000     17    Sara      Q1 2025-04-16  April
12    Laptop  North  165000     57   Ahmed      Q1 2025-04-17  April
13     Mouse  South   24000     66  Ayesha      Q1 2025-04-18  April
14  Keyboard   East   42000     89   Bilal      Q1 2025-04-19  April
15   Monitor   West  105000     54   Hamza      Q2 2025-04-20  April
16    Laptop  North  180000     12  Zainab      Q2 2025-04-21  April
17     Mouse  South   27000     85   Usman      Q2 2025-04-22  April
18  Keyboard   East   48000     29  Fatima      Q2 2025-04-23  April
19   Monitor   West  115000     39  Hassan      Q2 2025-04-24  April
20    Laptop  North  195000     86     Ali      Q2 2025-04-25  April
21     Mouse  South   30000     16    Sara      Q2 2025-04-26  April
22  Keyboard   East   55000     32   Ahmed      Q2 2025-04-27  April
23   Monitor   West  125000     43  Ayesha      Q2 2025-04-28  April
24    Laptop  North  210000     32   Bilal      Q2 2025-04-29  April
25     Mouse  South   33000     90   Hamza      Q2 2025-04-30  April
26  Keyboard   East   62000     87  Zainab      Q2 2025-05-01    May
27   Monitor   West  135000     72   Usman      Q2 2025-05-02    May
28    Laptop  North  225000     66  Fatima      Q2 2025-05-03    May
29     Mouse  South   36000     24  Hassan      Q2 2025-05-04    May

In [21]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product')

Product      Keyboard    Laptop   Monitor    Mouse
Region
East     41714.285714       NaN       NaN      NaN
North             NaN  172500.0       NaN      NaN
South             NaN       NaN       NaN  25500.0
West              NaN       NaN  105000.0      NaN

In [22]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median')

Product  Keyboard    Laptop   Monitor    Mouse
Region
East      42000.0       NaN       NaN      NaN
North         NaN  172500.0       NaN      NaN
South         NaN       NaN       NaN  25500.0
West          NaN       NaN  105000.0      NaN

In [24]:
pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')

                Sales                                   Units         \
Product      Keyboard    Laptop   Monitor    Mouse   Keyboard Laptop
Region
East     41714.285714       NaN       NaN      NaN  50.857143    NaN
North             NaN  172500.0       NaN      NaN        NaN   57.0
South             NaN       NaN       NaN  25500.0        NaN    NaN
West              NaN       NaN  105000.0      NaN        NaN    NaN


Product    Monitor   Mouse
Region
East           NaN     NaN
North          NaN     NaN
South          NaN  59.875
West     40.714286     NaN

In [26]:
pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product',aggfunc='median')

           Sales                                 Units
Product Keyboard    Laptop   Monitor    Mouse Keyboard Laptop Monitor Mouse
Region
East     42000.0       NaN       NaN      NaN     40.0    NaN     NaN   NaN
North        NaN  172500.0       NaN      NaN      NaN   61.5     NaN   NaN
South        NaN       NaN       NaN  25500.0      NaN    NaN     NaN  71.0
West         NaN       NaN  105000.0      NaN      NaN    NaN    41.0   NaN

In [27]:
##CROSS TAB:

In [28]:
pd.crosstab(df['Region'],df['Product'])

Product  Keyboard  Laptop  Monitor  Mouse
Region
East            7       0        0      0
North           0       8        0      0
South           0       0        0      8
West            0       0        7      0